### ISSUE TITLE
Add support for Clippy Local Git hooks 

### ISSUE THREAD

**Issue by satlead** [rdkcentral/Ripple#184]
Code committed to the repository should be in a consistent format and of the highest quality. Code quality can be checked using the Rust linting tool `clippy` and formatting achieved with `rustfmt`. Both of these tools can be run through cargo.

Rather than asking contributors to run these commands before pushing code we can get them run on a git pre-commit hook and save them some time.

**Comment by adamdama** [comment]
Closed with: https://github.com/rdkcentral/Ripple/pull/216
