### ISSUE TITLE
Refactor code for better readability and memory consumption

### ISSUE THREAD

**Issue by satlead** [rdkcentral/Ripple#197]
- [x] Add `unwrap_or_default` for conditional statements which unwrap to a boolean 
- [x] Reduce clones and object ownership transfers like `PermissionHandler::fetch_and_store(..` try using references
- [x] Reduce clone for appId, method references in CallContext like `ctx.clone().app_id` replace it with ctx.app_id.to_owned

**Comment by adamdama** [comment]
All of these issues have been address in the linked [PR](https://github.com/rdkcentral/Ripple/pull/198)
