### ISSUE TITLE
Loop that never loops

### ISSUE THREAD

**Issue by adamdama** [rdkcentral/Ripple#199]
During the process of addressing clippy warnings on the code base I found a for loop that never actually loops. I have attached screenshots of the code block and error. Code is [here](https://github.com/rdkcentral/Ripple/blob/f466ae6bc75dd3bc26a5a9a41dfc5e272b505e2f/core/main/src/service/user_grants.rs#L897)

![Screenshot 2023-08-09 at 09 15 30](https://github.com/rdkcentral/Ripple/assets/2086479/c7baa2ab-f9b8-4848-8f80-b19e98f65b11)
![Screenshot 2023-08-09 at 09 15 37](https://github.com/rdkcentral/Ripple/assets/2086479/c3d5211d-2295-427c-8653-5013ed938efb)

If you look at the branches in the inner loop all of them contain a `return` statement, therefore the loop will exit on the first iteration no matter what. I can of course refactor this to use `.iter().next()` and just handle the first case but I am concerned that this is not the intention of this code.

It would be great to get some guidance on how the `evaluate_options` function is supposed to work so that I can address the problem in the most appropriate way.

**Comment by satlead** [comment]
Believe the if condition should be moved outside the loop as we already have the info we need to call that condition.
