### ISSUE TITLE
Create Issue Template

### ISSUE THREAD

**Issue by adamdama** [rdkcentral/Ripple#222]
As development in Ripple expands to more contributors more and more Issues are going to be raised on the project. With current plans to manage all work that goes into the codebase through Issues it is going to be essential that raised issues are in a consistent format and contain enough information that they can be assessed and prioritised. Therefore we should create an Issue template that will serve as the basis for all raised issues.

We should follow the GitHub guidelines here to achieve this: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#issue-templates

**Comment by satlead** [comment]
https://github.com/rdkcentral/Ripple/pull/221
